### PR TITLE
Contributions

### PR DESCRIPTION
**Pull request by freq-mod**
#Before and during Christmas I made some tweaks, redos etc:
>Glockenspiel - finally sounds somewhat good, 4op (Fixes issue #32 )
>Clavinet - matches SC-55 much more
>Nylon Guitar - ditto, added string pluck sound
>008:024 GS Ukulele
>008:014 GS Tubular Bells
>008:026 GS Hawaian Gt.
>couple of drums for a future GS TR-808 Drumkit (Closed and Open Hi-hats, Snare 1)
>few GS organs candidates 
>Electric Snare (slight volume tweak)
>Electric Clean Guitar (closer to SC-55)
>Bass & Lead (ditto, it's a modified Clavinet
>Fifths Lead (previous one was slightly too "soft"
>Koto (previous one broke one particular MIDI seq, I had to redo it)
>Voice Oohs (attempt to match SC-55)
>Music Box (slight improvement, closer to Sound Canvas)

The rest (before "Bye GM" commit) was implemented before; sorry for the mess.

### CODE REVIEW

**Comment by sneakernets** [comment]
It's alright! Seeing your WOPL file actually helps me :)

**Comment by sneakernets** [comment]
Actually @papiezak how are you implementing these GS instruments in the editor? I'm a little ignorant on that for some reason.

**Comment by freq-mod** [comment]
@sneakernets i'm not implementing these in editor xD
I guess it's something about LSB, but I'm not 100% sure
Also I don't remember whether my .wopl file contains all of these instruments
EDIT: Room Drumkit: you set LSB parameter to 8,
Power - 16 etc.

http://www.voidaudio.net/percussion.html
http://www.voidaudio.net/gminstrument.html
http://www.voidaudio.net/gsinstrument.html

**Comment by sneakernets** [comment]
Maybe Wohlstand would know, heh

**Comment by Wohlstand** [comment]
I wasn't wrote a manual for that, but I'll explain in short words:

If you want to add a new bank, Edit -> Add Bank. Then use pencil icon to edit name of the bank and set MSB/LSB that will tell which MIDI bank ID will be used to alias this bank while playing MIDI files.

Note: Multi-bank will work for custom-loaded banks only and will not work when you will build it as embedded bank by ADLDATA generator as existing structure allows GM-only banks.

**Comment by freq-mod** [comment]
@sneakernets i'm implementing these into .wopl file, wait a sec
 Here it is: 640cb59

**Comment by sneakernets** [comment]
I really wish I could load and save individual "sub banks" rather than all of them at once. 🤔

**Comment by sneakernets** [comment]
okay I'm going to add these in one at a time as I get the chance. First stop, those new guiros

**Comment by sneakernets** [comment]
Thanks! I've been so busy with stuff that I haven't had a good time to look at these, but I will look at them this week!

**Comment by freq-mod** [comment]
Just a reminder - check out basses from a89c3a9 and new toms. It's worth it.

**Comment by sneakernets** [comment]
Hiiiiii I've been kind of out of it, Rarely changing stuff, But I'm going to look at this stuff today! finally!

I'm also going to separate contribs into folders if I can

**Pull request closed without merging**
