### PR TITLE
New contributions

### PR DESCRIPTION
**Pull request by freq-mod**
-random FX tweaks
-a few percussive GS instruments
-experimental GS melodic instruments (Piano and Feedback Gt.)
-glockenspiel patch that i tried to improve, but failed, that can be fixed though

You can ignore the rest. :D

### CODE REVIEW

**Comment by Wohlstand** [comment]
Be sure that DMX OP2 has stripped percussion range to store GM set at bassdrum up to open triangle.

**Comment by freq-mod** [comment]
DMX .op2 version is alright. GS changes are WOPL exclusive.

**Comment by Wohlstand** [comment]
I think, you are also can provide XG standard variant too (you are able to use software Yamaha S-YXG50 which is still available, but working well on Windows 9x or Windows NT/2000/XP but it failed to work on Windows 7 at me).
I even have implemented some XG controllers, for example, 74'th Brightness (at my libraries that are scaling modulators). And at me is works the XG-way to turn any channel into percussion. For GS way I need to handle SysEx events I need to learn more deeply.

**Comment by freq-mod** [comment]
XG variant support is planned too, but for now I think priority is to make GM sound bank sound reasonable and compatible with SC-55/SC-88 which represents GS standart.

**Comment by sneakernets** [comment]
Oh snap, I'll look into this

**Comment by sneakernets** [comment]
@papiezak yes that's exactly the goal right now, just getting GS support in.

**Pull request closed without merging**
